module CardSets
  #vintage editions; cards which may have two-letter set codes
  VintageEditions = {
    "Alpha" => "LEA",
    "Beta" => "LEB",
    "Unlimited" => "2ED",
    "Revised" => "3ED",
    "Fourth Edition" => "4ED",
    "Chronicles" => "CHR",
    "Fifth Edition" => "5ED",
    "Sixth Edition" => "6ED",
    "Seventh Edition" => "7E",
    "Eighth Edition" => "8ED",
    "Ninth Edition" => "9ED",
    "Tenth Edition" => "10E",
    
    "Arabian Nights" => "ARN",
    "Antiquities" => "ATQ",
    "Legends" => "LEG",
    "The Dark" => "DRK",
    "Fallen Empires" => "FEM",

    "Ice Age" => "ICE",
    "Homelands" => "HML",
    "Alliances" => "ALL",

    "Mirage" => "MI",
    "Visions" => "VI",
    "Weatherlight" => "WL",

    "Tempest" => "TE",
    "Stronghold" => "ST",
    "Exodus" => "EX",

    "Urza's Saga" => "UZ",
    "Urza's Legacy"=>"UL",
    "Urza's Destiny"=>"UD",

    "Mercadian Masques"=>"MM",
    "Nemesis" => "NE",
    "Prophecy" => "PR",

    "Invasion" => "IN",
    "Planeshift" => "PS",
    "Apocalypse" => "AP",

    "Odyssey" => "OD",
    "Torment" => "TOR",
    "Judgment" => "JUD",

    "Unglued" => "UGL"
  }

  CategoriedEditions = {
    "Vintage" =>  {
      "Alpha"=>"LEA",
      "Beta"=>"LEB",
      "Unlimited"=>"2ED",
      "Revised"=>"3ED",
      "Fourth Edition"=>"4ED",
      "Fifth Edition"=>"5ED",
      "Sixth Edition"=>"6ED",
      "Seventh Edition" => "7E",
      "Arabian Nights"=>"ARN",
      "Antiquities"=>"ATQ",
      "Legends"=>"LEG",
      "The Dark"=>"DRK",
      "Fallen Empires"=>"FEM",
      "Ice Age"=>"ICE",
      "Homelands"=>"HML",
      "Alliances"=>"ALL",
      "Mirage"=>"MI",
      "Visions"=>"VI",
      "Weatherlight"=>"WL",
      "Tempest"=>"TE",
      "Stronghold"=>"ST",
      "Exodus"=>"EX",
      "Portal" => "POR",
      "Urza's Saga"=>"UZ",
      "Urza's Legacy"=>"UL",
      "Urza's Destiny"=>"UD",
      "Mercadian Masques"=>"MM",
      "Nemesis" => "NE",
      "Prophecy"=>"PR",
      "Invasion" => "IN",
      "Planeshift"=>"PS",
      "Apocalypse"=>"AP",
      "Odyssey"=>"OD",
      "Judgment"=>"JUD",
      "Torment"=>"TOR",
      "Onslaught"=>"ONS",
      "Legions" => "LGN",
      "Scourge" => "SCG"
    },
    "Modern" => { 
      "Mirrodin"=>"MRD",
      "Darksteel" => "DST",
      "Fifth Dawn"=>"5DN",
      "Champions of Kamigawa"=>"CHK",
      "Betrayers of Kamigawa" => "BOK",
      "Saviors of Kamigawa"=>"SOK",
      "Ravnica: City of Guilds" => "RAV",
      "Guildpact" => "GPT",
      "Dissension" => "DIS",
      "Coldsnap"=>"CSP",
      "Time Spiral" => "TSB" ,
      "Time Spiral Timeshifted" => "TSP",
      "Planar Chaos" => "PLC",
      "Future Sight" => "FUT",
      "Lorwyn" => "LRW",
      "Morningtide" => "MOR",
      "Shadowmoor" => "SHM",
      "Eventide" => "EVE",
      "Shards of Alara" => "ALA",
      "Conflux" => "CON",
      "Alara Reborn" => "ARB",
      "Zendikar"=>"ZEN",
      "Worldwake" => "WWK",
      "Rise of the Eldrazi" => "ROE",
      "Scars of Mirrodin"=>"SOM",
      "Mirrodin Besieged" => "MBS",
      "New Phyrexia" => "NPH",
      "Innistrad"=>"ISD",
      "Dark Ascension" => "DKA",
      "Avacyn Restored"=>"AVR",
      "Return to Ravnica" => "RTR",
      "Gatecrash"=>"GTC",
      "Dragon's Maze" => "DGM",
      "Theros" => "THS",
      "Born of the Gods" => "BNG",
      "Journey into Nyx" => "JOU",
      "Khans of Tarkir" => "KTK",
      "Fate Reforged" => "FRF",
      "Dragons of Tarkir" => "DTK",
      "Battle for Zendikar" => "BFZ",
      "Oath of the Gatewatch" => "OGW",
      "Shadows over Innistrad"=>"SOI",
      "Eldritch Moon" => "EMN",
      "Kaladesh" => "KLD",
      "Aether Revolt" => "AER",
      "Amonkhet" => "AKH",
      "Hour of Devastation" => "HOU",
    },
    "Standard" => {
      "Ixalan" => "XLN",
      "Rivals of Ixalan" => "RIX",
      "Dominaria" => "DOM",
      "Core Set 2019"=>"M19",
      "Guilds of Ravnica" => "GRN",
      "Ravnica Allegiance" => "RNA",
      "War of the Spark" => "WAR",
      "Core Set 2020" => "M20"
    },
    "Core Sets" => {
      "Eighth Edition" => "8ED",
      "Ninth Edition" => "9ED",
      "Tenth Edition" => "10E",
      "Magic 2010"=> "M10",
      "Magic 2011"=> "M11",
      "Magic 2012"=> "M12",
      "Magic 2013" => "M13",
      "Magic 2014" => "M14",
      "Magic 2015" => "M15",
      "Magic Origins"=>"ORI",
    }, 
    "Commander" => {
      "Commander" => "CMD",
      "Commander's Arsenal" => "CM1",
      "Commander 2013" => "C13",
      "Commander 2014" => "C14",
      "Commander 2015" => "C15",
      "Commander 2016" => "C16",
      "Commander 2017" => "C17",
      "Commander 2018" => "C18"
    },
    "Masters" => {
      "Modern Masters" => "MMA",
      "Modern Masters 2015" => "MM2",
      "Modern Masters 2017" => "MM3",
      "Eternal Masters" => "EMA",
      "Iconic Masters" => "IMA",
      "Masters 25" => "A25",
      "Ultimate Masters" => "UMA",
      "Ultimate Box Topper" => "PUMA",
      "Modern Horizons" => "MH1"
    },
    "From the Vault" => {
      "From the Vault: Dragons" => "DRB",
      "From the Vault: Exiled" => "V09",
      "From the Vault: Relics" => "V10",
      "From the Vault: Legends" => "V11",
      "From the Vault: Realms" => "V12",
      "From the Vault: Twenty" => "V13",
      "From the Vault: Annihilation" => "V14",
      "From the Vault: Angels" => "V15",
      "From the Vault: Lore" => "V16",
      "From the Vault: Transform" => "V17"
    },
    "Masterpiece Sets" => {
      "Zendikar Expeditions" => "EXP",
      "Kaladesh Inventions" => "MS2",
      "Amonkhet Invocations" => "MS3",
      "Ravnica Allegiance Mythic Edition" => "MED"
    },
    "Un-Sets" => {
      "Unglued" => "UGL", 
      "Unhinged" => "UNH",
      "Unstable" => "UST"
    }
  };

  AllEditionsStandardCodes = {
  #vintage
    "Alpha"=>"LEA",
    "Beta"=>"LEB",
    "Unlimited"=>"2ED",
    "Revised"=>"3ED",
    "Chronicles" => "CHR",
    "Fourth Edition"=>"4ED",
    "Fifth Edition"=>"5ED",
    "Sixth Edition"=>"6ED",
    "Seventh Edition" => "7ED",
    "Eighth Edition" => "8ED",
    "Ninth Edition" => "9ED",
    "Tenth Edition" => "10E",
    "Arabian Nights"=>"ARN",
    "Antiquities"=>"ATQ",
    "Legends"=>"LEG",
    "The Dark"=>"DRK",
    "Fallen Empires"=>"FEM",
    "Ice Age"=>"ICE",
    "Homelands"=>"HML",
    "Alliances"=>"ALL",
    "Mirage"=>"MIR",
    "Visions"=>"VIS",
    "Weatherlight"=>"WTH",
    "Tempest"=>"TMP",
    "Stronghold"=>"STH",
    "Exodus"=>"EXO",
    "Portal" => "POR",
    "Urza's Saga"=>"USG",
    "Urza's Legacy"=>"ULG",
    "Urza's Destiny"=>"UDS",
    "Mercadian Masques"=>"MMQ",
    "Nemesis" => "NEM",
    "Prophecy"=>"PCY",
    "Invasion" => "INV",
    "Planeshift"=>"PLS",
    "Apocalypse"=>"APC",
    "Odyssey"=>"ODY",
    "Torment"=>"TOR",
    "Judgment"=>"JUD",
    "Onslaught"=>"ONS",
    "Legions" => "LGN",
    "Scourge" => "SCG",
   #modern
    "Mirrodin"=>"MRD",
    "Darksteel" => "DST",
    "Fifth Dawn"=>"5DN",
    "Champions of Kamigawa"=>"CHK",
    "Betrayers of Kamigawa" => "BOK",
    "Saviors of Kamigawa"=>"SOK",
    "Ravnica: City of Guilds" => "RAV",
    "Guildpact" => "GPT",
    "Dissension" => "DIS",
    "Coldsnap"=>"CSP",
    "Time Spiral" => "TSP",
    "Time Spiral Timeshifted" => "TSB",
    "Planar Chaos" => "PLC",
    "Future Sight" => "FUT",
    "Lorwyn" => "LRW",
    "Morningtide" => "MOR",
    "Shadowmoor" => "SHM",
    "Eventide" => "EVE",
    "Shards of Alara" => "ALA",
    "Conflux" => "CON",
    "Alara Reborn" => "ARB",
    "Zendikar"=>"ZEN",
    "Worldwake" => "WWK",
    "Rise of the Eldrazi" => "ROE",
    "Scars of Mirrodin"=>"SOM",
    "Mirrodin Besieged" => "MBS" ,
    "New Phyrexia" => "NPH",
    "Innistrad"=>"ISD",
    "Dark Ascension" => "DKA",
    "Avacyn Restored"=>"AVR",
    "Return to Ravnica" => "RTR",
    "Gatecrash"=>"GTC",
    "Dragon's Maze" => "DGM",
    "Theros" => "THS",
    "Born of the Gods" => "BNG",
    "Journey into Nyx" => "JOU",
    "Khans of Tarkir" => "KTK",
    "Fate Reforged" => "FRF",
    "Dragons of Tarkir" => "DTK",
    "Zendikar Expeditions" => "EXP",
    "Battle for Zendikar" => "BFZ",
    "Oath of the Gatewatch" => "OGW",
    "Shadows over Innistrad"=>"SOI",
    "Eldritch Moon" => "EMN",
    "Kaladesh Inventions" => "MS2",
    "Kaladesh" => "KLD",
    "Aether Revolt" => "AER",
    "Amonkhet Invocations" => "MS3", #MP2 for scryfall
    "Amonkhet" => "AKH",
    "Hour of Devastation" => "HOU",
    #standard
    "Ixalan" => "XLN",
    "Rivals of Ixalan" => "RIX",
    "Dominaria" => "DOM",
    "Guilds of Ravnica" => "GRN",
    "Ravnica Allegiance" => "RNA",
    "Ravnica Allegiance Mythic Edition" => "MED",
    "War of the Spark" => "WAR",

    #core sets
    "Magic 2010" => "M10",
    "Magic 2011" => "M11",
    "Magic 2012" => "M12",
    "Magic 2013" => "M13",
    "Magic 2014" => "M14",
    "Magic 2015" => "M15",
    "Magic Origins" => "ORI",
    "Core Set 2019" => "M19",
    "Core Set 2020" => "M20",

    #commander
    "Commander" => "CMD",
    "Commander's Arsenal" => "CM1",
    "Commander 2013" => "C13",
    "Commander 2014" => "C14",
    "Commander 2015" => "C15",
    "Commander 2016" => "C16",
    "Commander Anthology" => "CMA",
    "Commander 2017" => "C17",
    "Commander 2018" => "C18",

    "Unglued" => "UGL", 
    "Unhinged" => "UNH",
    "Unstable" => "UST",
    
    #masters
    "Modern Masters" => "MMA",
    "Modern Masters 2015" => "MM2",
    "Modern Masters 2017" => "MM3",
    "Eternal Masters" => "EMA",
    "Iconic Masters" => "IMA",
    "Masters 25" => "A25",
    "Ultimate Masters" => "UMA",
    "Ultimate Box Topper" => "PUMA", #PRM-UMA for MTGGoldfish
    "Modern Horizons" => "MH1",

    "Portal Second Age" => "PO2",
    "Portal Three Kingdoms" => "PTK",

    "Conspiracy" => "CNS",
    "Conspiracy: Take the Crown" => "CN2",

    "From the Vault: Dragons" => "DRB",
    "From the Vault: Exiled" => "V09",
    "From the Vault: Relics" => "V10",
    "From the Vault: Legends" => "V11",
    "From the Vault: Realms" => "V12",
    "From the Vault: Twenty" => "V13",
    "From the Vault: Annihilation" => "V14",
    "From the Vault: Angels" => "V15",
    "From the Vault: Lore" => "V16",
    "From the Vault: Transform" => "V17",

    #editions that aren't sorted or added yet

    # "Starter 1999" => "S99",
    # "Starter 2000" => "S00",
    # "Anthologies" => "ATH",

    #duel decks
    
    # "DD: Elves vs. Goblins" => "EVG",
    # "DD: Jace vs. Chandra" => "DD2",
    # "DD: Divine vs. Demonic" => "DDC",
    # "DD: Garruk vs. Liliana" => "DDD",
    # "DD: Phyrexia vs. the Coalition" => "DDE",
    # "DD: Elspeth vs. Tezzeret" => "DDF",
    # "DD: Knights vs. Dragons" => "DDG",
    # "DD: Ajani vs. Nicol Bolas" => "DDH",
    # "DD: Venser vs. Koth" => "DDI",
    # "DD: Izzet vs. Golgari" => "DDJ",
    # "DD: Sorin vs. Tibalt" => "DDK",
    # "DD: Heroes vs. Monsters" => "DDL",
    # "DD: Jace vs. Vraska" => "DDM",
    # "DD: Speed vs. Cunning" => "DDN",
    # "DD: Elspeth vs. Kiora" => "DDO",
    # "DD: Zendikar vs. Eldrazi" => "DDP",
    # "DD: Blessed vs Cursed" => "DDQ",
    # "DD: Nissa vs. Ob Nixilis" => "DDR",
    # "DD: Anthology" => "DD3_JVC",
    # "DD: Anthology" => "DD3_GVL",
    # "DD: Anthology" => "DD3_EVG",
    # "DD: Anthology" => "DD3_DVD",
    # "DD: Mind vs. Might" => "DDS",
    # "DD: Merfolk vs. Goblins" => "DDT",
    # "DD: Elves vs. Inventors" => "DDU"
  };

  SET_CODES_IN_CHRONOLOGICAL_ORDER = AllEditionsStandardCodes.invert.map.with_index { | (set_code, _), idx | [set_code, idx] }.to_h
  SET_NAMES_IN_CHRONOLOGICAL_ORDER = AllEditionsStandardCodes.map.with_index { | (set_code, _), idx | [set_code, idx] }.to_h

end
