module Cards

  Editions = {
    "Alpha" => "LEA",
    "Beta" => "LEB",
    "Unlimited" => "2ED",
    "Revised" => "3ED",
    "Fourth Edition" => "4ED",
    "Chronicles" => "CHR",
    "Fifth Edition" => "5ED",
    "Sixth Edition" => "6ED",
    "Seventh Edition" => "7E",
    "Eighth Edition" => "8ED",
    "Ninth Edition" => "9ED",
    "Tenth Edition" => "10E",
    
    "Arabian Nights" => "ARN",
    "Antiquities" => "ATQ",
    "Legends" => "LEG",
    "The Dark" => "DRK",
    "Fallen Empires" => "FEM",

    "Ice Age" => "ICE",
    "Homelands" => "HML",
    "Alliances" => "ALL",

    "Mirage" => "MI",
    "Visions" => "VI",
    "Weatherlight" => "WL",

    "Tempest" => "TE",
    "Stronghold" => "ST",
    "Exodus" => "EX",

    "Urza's Saga" => "UZ",
    "Urza's Legacy"=>"UL",
    "Urza's Destiny"=>"UD",

    "Mercadian Masques"=>"MM",
    "Nemesis" => "NE",
    "Prophecy" => "PR",

    "Unglued" => "UGL"
  }

  CategoriedEditions = {
    "Vintage" =>  {
      "Alpha"=>"LEA",
      "Beta"=>"LEB",
      "Unlimited"=>"2ED",
      "Revised"=>"3ED",
      "Fourth Edition"=>"4ED",
      "Fifth Edition"=>"5ED",
      "Sixth Edition"=>"6ED",
      "Arabian Nights"=>"ARN",
      "Antiquities"=>"ATQ",
      "Legends"=>"LEG",
      "The Dark"=>"DRK",
      "Fallen Empires"=>"FEM",
      "Ice Age"=>"ICE",
      "Homelands"=>"HML",
      "Alliances"=>"ALL",
      "Mirage"=>"MI",
      "Visions"=>"VI",
      "Weatherlight"=>"WL",
      "Tempest"=>"TE",
      "Stronghold"=>"ST",
      "Exodus"=>"EX",
      "Portal" => "POR",
      "Urza's Saga"=>"UZ",
      "Urza's Legacy"=>"UL",
      "Urza's Destiny"=>"UD",
      "Mercadian Masques"=>"MM",
      "Nemesis" => "NE",
      "Prophecy"=>"PR",
      "Invasion" => "IN",
      "Planeshift"=>"PS",
      "Apocalypse"=>"AP",
      "Odyssey"=>"OD",
      "Judgment"=>"JUD",
      "Torment"=>"TOR",
      "Onslaught"=>"ONS",
      "Legions" => "LGN",
      "Scourge" => "SCG"
    },
    "Modern" => { 
      "Mirrodin"=>"MRD",
      "Darksteel" => "DST",
      "Fifth Dawn"=>"5DN",
      "Champions of Kamigawa"=>"CHK",
      "Betrayers of Kamigawa" => "BOK",
      "Saviors of Kamigawa"=>"SOK",
      "Ravnica: City of Guilds" => "RAV",
      "Guildpact" => "GPT",
      "Dissension" => "DIS",
      "Coldsnap"=>"CSP",
      "Time Shifted" => "TSB" ,
      "Time Spiral Timeshifted" => "TSP",
      "Planar Chaos" => "PLC",
      "Future Sight" => "FUT",
      "Lorwyn" => "LRW",
      "Morningtide" => "MOR",
      "Shadowmoor" => "SHM",
      "Eventide" => "EVE",
      "Shards of Alara" => "ALA",
      "Conflux" => "CON",
      "Alara Reborn" => "ARB",
      "Zendikar"=>"ZEN",
      "Worldwake" => "WWK",
      "Rise of the Eldrazi" => "ROE",
      "Scars of Mirrodin"=>"SOM",
      "Mirrodin Besieged" => "MBS" ,
      "New Phyrexia" => "NPH",
      "Innistrad"=>"ISD",
      "Dark Ascension" => "DKA",
      "Avacyn Restored"=>"AVR",
      "Return to Ravnica" => "RTR",
      "Gatecrash"=>"GTC",
      "Dragon's Maze" => "DGM",
      "Theros" => "THS",
      "Born of the Gods" => "BNG",
      "Journey into Nyx" => "JOU",
      "Shadows over Innistrad"=>"SOI",
      "Amonkhet"=>"AKH", 
      "Ixalan" => "XLN",
      "Rivals of Ixalan" => "RIX",
      "Kaladesh" => "KLD",
      "Hour of Devastation" => "HOU",
      "Aether Revolt" => "AER" ,
      "Battle for Zendikar" => "BFZ" 
    },
    "Core Sets" => {
      "Magic 2010"=> "M10",
      "Magic 2011"=> "M11",
      "Magic 2012"=> "M12",
      "Magic 2013" => "M13",
      "Magic 2014" => "M14",
      "Magic 2015" => "M15",
      "Magic Origins"=>"ORI",
      "Core Set 2019"=>"M19" 
    }, 
    "Commander" => {
      "Commander" => "CMD",
      "Commander 2013" => "C13"
    },
    "Un-Sets" => {
      "Unglued" => "UGL", 
      "Unhinged" => "UNH"
    }
  };

  AllEditionsStandardCodes = {
    "Alpha"=>"LEA",
    "Beta"=>"LEB",
    "Unlimited"=>"2ED",
    "Revised"=>"3ED",
    "Chronicles" => "CHR",
    "Fourth Edition"=>"4ED",
    "Fifth Edition"=>"5ED",
    "Sixth Edition"=>"6ED",
    "Seventh Edition" => "7ED",
    "Eighth Edition" => "8ED",
    "Ninth Edition" => "9ED",
    "Tenth Edition" => "10E",
    "Arabian Nights"=>"ARN",
    "Antiquities"=>"ATQ",
    "Legends"=>"LEG",
    "The Dark"=>"DRK",
    "Fallen Empires"=>"FEM",
    "Ice Age"=>"ICE",
    "Homelands"=>"HML",
    "Alliances"=>"ALL",
    "Mirage"=>"MIR",
    "Visions"=>"VIS",
    "Weatherlight"=>"WTL",
    "Tempest"=>"TMP",
    "Stronghold"=>"STH",
    "Exodus"=>"EXO",
    "Portal" => "POR",
    "Urza's Saga"=>"USG",
    "Urza's Legacy"=>"ULG",
    "Urza's Destiny"=>"UDS",
    "Mercadian Masques"=>"MMQ",
    "Nemesis" => "NEM",
    "Prophecy"=>"PCY",
    "Invasion" => "INV",
    "Planeshift"=>"PLS",
    "Apocalypse"=>"APC",
    "Odyssey"=>"ODY",
    "Torment"=>"TOR",
    "Judgment"=>"JUD",
    "Onslaught"=>"ONS",
    "Legions" => "LGN",
    "Scourge" => "SCG",

    "Mirrodin"=>"MRD",
    "Darksteel" => "DST",
    "Fifth Dawn"=>"5DN",
    "Champions of Kamigawa"=>"CHK",
    "Betrayers of Kamigawa" => "BOK",
    "Saviors of Kamigawa"=>"SOK",
    "Ravnica: City of Guilds" => "RAV",
    "Guildpact" => "GPT",
    "Dissension" => "DIS",
    "Coldsnap"=>"CSP",
    "Time Spiral" => "TSP",
    "Time Spiral Timeshifted" => "TSB",
    "Planar Chaos" => "PLC",
    "Future Sight" => "FUT",
    "Lorwyn" => "LRW",
    "Morningtide" => "MOR",
    "Shadowmoor" => "SHM",
    "Eventide" => "EVE",
    "Shards of Alara" => "ALA",
    "Conflux" => "CON",
    "Alara Reborn" => "ARB",
    "Zendikar"=>"ZEN",
    "Worldwake" => "WWK",
    "Rise of the Eldrazi" => "ROE",
    "Scars of Mirrodin"=>"SOM",
    "Mirrodin Besieged" => "MBS" ,
    "New Phyrexia" => "NPH",
    "Innistrad"=>"ISD",
    "Dark Ascension" => "DKA",
    "Avacyn Restored"=>"AVR",
    "Return to Ravnica" => "RTR",
    "Gatecrash"=>"GTC",
    "Dragon's Maze" => "DGM",
    "Theros" => "THS",
    "Born of the Gods" => "BNG",
    "Journey into Nyx" => "JOU",
    "Shadows over Innistrad"=>"SOI",
    "Amonkhet"=>"AKH", 
    "Ixalan" => "XLN",
    "Rivals of Ixalan" => "RIX",
    "Kaladesh" => "KLD",
    "Hour of Devastation" => "HOU",
    "Aether Revolt" => "AER" ,
    "Battle for Zendikar" => "BFZ",

    "Magic 2010" => "M10",
    "Magic 2011" => "M11",
    "Magic 2012" => "M12",
    "Magic 2013" => "M13",
    "Magic 2014" => "M14",
    "Magic 2015" => "M15",
    "Magic Origins" => "ORI",
    "Core Set 2019" => "M19",

    "Commander" => "CMD",
    "Commander 2013" => "C13",
    # "Commander 2014" => "C14",
    # "Commander 2015" => "C15",
    # "Commander 2016" => "C16",
    # "Commander Anthology" => "CMA",
    # "Commander 2017" => "C17",
    # "Commander 2018" => "C18",

    "Unglued" => "UGL", 
    "Unhinged" => "UNH",
    # "Unstable" => "UST",

    #editions that aren't sorted or added yet

    "Anthologies" => "ATH",
    
    # "Modern Masters" => "MMA",
    # "Modern Masters 2015" => "MM2",
    # "Eternal Masters" => "EMA",
    # "Iconic Masters" => "IMA",
    # "Masters 25" => "A25",
    # "Ultimate Masters" => "UMA",

    # "Portal Second Age" => "PO2",
    # "Portal Three Kingdoms" => "PTK",
    # "Starter 1999" => "S99",
    # "Starter 2000" => "S00",

    # "Conspiracy" => "CNS",

    # "From The Vault: Dragons" => "DRB",
    # "From The Vault: Exiled" => "V09",
    # "From The Vault: Relics" => "V10",
    # "From The Vault: Legends" => "V11",
    # "From The Vault: Realms" => "V12",
    # "From The Vault: Twenty" => "V13",
    # "From The Vault: Annihilation" => "V14",
    # "From The Vault: Angels" => "V15",
    # "From The Vault: Lore" => "V16",
    # "From The Vault: Transform" => "V17",

    # "DD: Elves vs. Goblins" => "EVG",
    # "DD: Jace vs. Chandra" => "DD2",
    # "DD: Divine vs. Demonic" => "DDC",
    # "DD: Garruk vs. Liliana" => "DDD",
    # "DD: Phyrexia vs. the Coalition" => "DDE",
    # "DD: Elspeth vs. Tezzeret" => "DDF",
    # "DD: Knights vs. Dragons" => "DDG",
    # "DD: Ajani vs. Nicol Bolas" => "DDH",
    # "DD: Venser vs. Koth" => "DDI",
    # "DD: Izzet vs. Golgari" => "DDJ",
    # "DD: Sorin vs. Tibalt" => "DDK",
    # "DD: Heroes vs. Monsters" => "DDL",
    # "DD: Jace vs. Vraska" => "DDM",
    # "DD: Speed vs. Cunning" => "DDN",
    # "DD: Elspeth vs. Kiora" => "DDO",
    # "DD: Zendikar vs. Eldrazi" => "DDP",
    # "DD: Blessed vs Cursed" => "DDQ",
    # "DD: Nissa vs. Ob Nixilis" => "DDR",
    # "DD: Anthology" => "DD3_JVC",
    # "DD: Anthology" => "DD3_GVL",
    # "DD: Anthology" => "DD3_EVG",
    # "DD: Anthology" => "DD3_DVD",
    # "DD: Mind vs. Might" => "DDS",
    # "DD: Merfolk vs. Goblins" => "DDT",
    # "DD: Elves vs. Inventors" => "DDU"


  };

end